### ISSUE TITLE
Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by superfein** [amoser67/shopify_dev_utils#1]
I'm running Node v-13+ on Windows 10. 

I've followed your instructions perfectly, yet when I type "node run" in the CLI I get this error: Cannot find module 'dotenv'

For some reason even after following your instructions a package.json file was never created. This may be the cause of the missing module error.

Any idea why no package.json file was created? The package-lock.json file was created.

**Comment by amoser67** [comment]
Ah, I think I understand whats going on.  So the run file that I used as an example has two dependencies, dotenv and shopify_dev_utils.  So in your project's root directory, you will need to do the following:

`npm init`
`npm i dotenv`
`npm i shopify_dev_utils`

If you have already done this, or you do it and are still having issues, let me know.

PS The instructions fail to mention `npm init` which would result in the errors you experienced, I will update them.

**Comment by superfein** [comment]
Thanks @amoser67 that fixed it! Now I'm getting a different error, I'll open a new issue for that.
