### ISSUE TITLE
How to upload and download products as JSON objects?

### ISSUE THREAD

**Issue by superfein** [amoser67/shopify_dev_utils#6]
In the docs you wrote "Enables one to upload and download products as JSON objects." How would I go about doing that? What's the process for download/upload?

P.S. I know I'm being rather pesky, if at any time you don't want to respond feel free. I'm just so keen on having the best possible Shopify dev workflow, and this setup you've created integrates a browser reload feature seamlessly with virtually zero config and with very little delay. All my attempts to use browser-sync with themekit/gulp have had huge delays of up to 3 seconds which is virtually unusable as it slows development too much.

**Comment by amoser67** [comment]
I need to add in the documentation for that stuff.  Here is an example until then though:
Create a file in your project root directory named whatever you want, e.g. post-products.js, which contains the following.  To execute it, type node post-products in the terminal.
~~~
const dotenv = require("dotenv").config();
const ShopifyDevUtils = require("shopify_dev_utils");
const data = Object.create(null);
  try {
    data.store_url = process.env.STORE_URL;
    data.theme_id  = process.env.THEME_ID;
    data.auth      = process.env.AUTH;`
    //  Make the product JSON objects we want to post.
    const product_data = [];
    let k = 1;
    while (k < 20) {
        let object = {
            "product": {
                "title": "Product Zeta " + k,
                "body_html": "",
                "vendor": "test-alpha-bravo",
                "product_type": "Zeta",
                "tags": [
                    "Zeta",
                    "Best Sellers"
                ],
                "variants": [
                    {
                        "title": "Black",
                        "option1": "Black",
                        "price": "24.99",
                        "compare-at-price": "34.99"
                    },
                    {
                        "title": "Gray",
                        "option1": "Gray",
                        "price": "24.99",
                        "compare-at-price": "34.99"
                    },
                    {
                        "title": "White",
                        "option1": "White",
                        "price": "24.99",
                        "compare-at-price": "34.99"
                    }
                ],
                "options": [
                    {
                        "name": "Color",
                        "values": [
                            "Black",
                            "Gray",
                            "White"
                        ]
                    }
                ]
            }
        };
        product_data.push(object);
        k += 1;
    }

    ShopifyDevUtils.post_products(data, product_data);

} catch (exception) {
    console.log("ERROR: ", exception);
}
~~~

**To get a list of products printed to the console:**

Create a file named something like get-products.js, and execute using node get-products in the terminal. get-products.js should contain the following.
~~~
const dotenv = require("dotenv").config();
const ShopifyDevUtils = require("shopify_dev_utils");
const data = Object.create(null);
try {
    data.store_url = process.env.STORE_URL;
    data.theme_id  = process.env.THEME_ID;
    data.auth      = process.env.AUTH;

    ShopifyDevUtils.get_products(data, "?fields=id,title");
} catch (exception) {
    console.log("ERROR: ", exception);
}
~~~

**Comment by amoser67** [comment]
These dont need to be separate files necessarily, but I found it was the easiest way atm to use them.
The post example shows how one could use this feature to quickly create a bunch of products for testing or otherwise.

**Comment by superfein** [comment]
Brilliant! Great example use case, to populate a staging store with products. Love working on the command line.
